export const defaultEvents = [
  {
    id: 1,
    title: "First Friday Art Walk",
    date: "2024-12-06",
    time: "17:00",
    location: "Haynie's Corner Arts District",
    city: "Evansville",
    state: "IN",
    category: "Arts & Culture",
    price: "Free",
    image: "https://picsum.photos/400/200?random=1",
    description: "Monthly art walk featuring local galleries, live music, and food vendors. Experience the vibrant arts community!",
    attendees: 234,
    organizer: "Downtown Arts Alliance"
  },
  {
    id: 2,
    title: "Jazz Night at The Centre",
    date: "2024-12-08",
    time: "19:30",
    location: "The Centre",
    city: "Evansville",
    state: "IN",
    category: "Music",
    price: "$15-25",
    image: "https://picsum.photos/400/200?random=2",
    description: "Live jazz performance featuring renowned local musicians in an intimate setting.",
    attendees: 89,
    organizer: "The Centre"
  },
  {
    id: 3,
    title: "Saturday Farmers Market",
    date: "2024-12-07",
    time: "08:00",
    location: "Main Street",
    city: "Evansville",
    state: "IN",
    category: "Food & Drink",
    price: "Free",
    image: "https://picsum.photos/400/200?random=3",
    description: "Weekly farmers market with local produce, crafts, and food trucks.",
    attendees: 456,
    organizer: "Downtown Market Association"
  },
  {
    id: 4,
    title: "Holiday Lights Festival",
    date: "2024-12-15",
    time: "18:00",
    location: "Garvin Park",
    city: "Evansville",
    state: "IN",
    category: "Family & Kids",
    price: "Free",
    image: "https://picsum.photos/400/200?random=4",
    description: "Annual holiday celebration with light displays, hot cocoa, and family activities.",
    attendees: 678,
    organizer: "Evansville Parks Department"
  },
  {
    id: 5,
    title: "Business Networking Breakfast",
    date: "2024-12-12",
    time: "07:30",
    location: "DoubleTree Hotel",
    city: "Evansville",
    state: "IN",
    category: "Business",
    price: "$25",
    image: "https://picsum.photos/400/200?random=5",
    description: "Monthly networking event for local business leaders and entrepreneurs.",
    attendees: 67,
    organizer: "Evansville Chamber of Commerce"
  },
  {
    id: 6,
    title: "Broadway Show: Hamilton",
    date: "2024-12-10",
    time: "20:00",
    location: "Tennessee Performing Arts Center",
    city: "Nashville",
    state: "TN",
    category: "Music",
    price: "$45-125",
    image: "https://picsum.photos/400/200?random=6",
    description: "The revolutionary musical about Alexander Hamilton comes to Nashville.",
    attendees: 1250,
    organizer: "Nashville Theatre"
  },
  {
    id: 7,
    title: "Music City Food Festival",
    date: "2024-12-09",
    time: "11:00",
    location: "Centennial Park",
    city: "Nashville",
    state: "TN",
    category: "Food & Drink",
    price: "$20",
    image: "https://picsum.photos/400/200?random=7",
    description: "Taste the best of Nashville's culinary scene with local restaurants and food trucks.",
    attendees: 2100,
    organizer: "Nashville Food & Wine"
  },
  {
    id: 8,
    title: "Honky Tonk Tuesday",
    date: "2024-12-10",
    time: "19:00",
    location: "The Stage on Broadway",
    city: "Nashville",
    state: "TN",
    category: "Music",
    price: "$10",
    image: "https://picsum.photos/400/200?random=8",
    description: "Live country music from upcoming artists and local bands.",
    attendees: 180,
    organizer: "The Stage"
  },
  {
    id: 9,
    title: "Nashville Tech Meetup",
    date: "2024-12-11",
    time: "18:30",
    location: "The Wond'ry",
    city: "Nashville",
    state: "TN",
    category: "Business",
    price: "Free",
    image: "https://picsum.photos/400/200?random=9",
    description: "Monthly meetup for Nashville's growing tech community.",
    attendees: 145,
    organizer: "Nashville Tech Community"
  },
  {
    id: 10,
    title: "Kentucky Derby Museum Tour",
    date: "2024-12-14",
    time: "10:00",
    location: "Churchill Downs",
    city: "Louisville",
    state: "KY",
    category: "Sports & Fitness",
    price: "$18",
    image: "https://picsum.photos/400/200?random=10",
    description: "Behind-the-scenes tour of the historic Churchill Downs and Derby Museum.",
    attendees: 89,
    organizer: "Churchill Downs"
  },
  {
    id: 11,
    title: "Bourbon Tasting Experience",
    date: "2024-12-13",
    time: "19:00",
    location: "Angel's Envy Distillery",
    city: "Louisville",
    state: "KY",
    category: "Food & Drink",
    price: "$35",
    image: "https://picsum.photos/400/200?random=11",
    description: "Guided tasting of premium Kentucky bourbon with distillery tour.",
    attendees: 45,
    organizer: "Angel's Envy"
  },
  {
    id: 12,
    title: "Waterfront Park Concert",
    date: "2024-12-08",
    time: "17:00",
    location: "Waterfront Park",
    city: "Louisville",
    state: "KY",
    category: "Music",
    price: "Free",
    image: "https://picsum.photos/400/200?random=12",
    description: "Free outdoor concert featuring local rock and indie bands.",
    attendees: 320,
    organizer: "Louisville Parks"
  },
  {
    id: 13,
    title: "Art Institute Special Exhibition",
    date: "2024-12-16",
    time: "10:00",
    location: "Art Institute of Chicago",
    city: "Chicago",
    state: "IL",
    category: "Arts & Culture",
    price: "$25",
    image: "https://picsum.photos/400/200?random=13",
    description: "New exhibition featuring contemporary American artists.",
    attendees: 567,
    organizer: "Art Institute of Chicago"
  },
  {
    id: 14,
    title: "Chicago Food Truck Rally",
    date: "2024-12-15",
    time: "12:00",
    location: "Millennium Park",
    city: "Chicago",
    state: "IL",
    category: "Food & Drink",
    price: "Free",
    image: "https://picsum.photos/400/200?random=14",
    description: "Over 50 food trucks featuring Chicago's diverse culinary scene.",
    attendees: 3200,
    organizer: "Chicago Food Truck Association"
  },
  {
    id: 15,
    title: "Second City Comedy Show",
    date: "2024-12-12",
    time: "20:00",
    location: "Second City",
    city: "Chicago",
    state: "IL",
    category: "Arts & Culture",
    price: "$28",
    image: "https://picsum.photos/400/200?random=15",
    description: "Hilarious improv comedy show at Chicago's legendary Second City.",
    attendees: 200,
    organizer: "Second City"
  },
  {
    id: 16,
    title: "Indianapolis Motor Speedway Tour",
    date: "2024-12-09",
    time: "11:00",
    location: "Indianapolis Motor Speedway",
    city: "Indianapolis",
    state: "IN",
    category: "Sports & Fitness",
    price: "$15",
    image: "https://picsum.photos/400/200?random=16",
    description: "Behind-the-scenes tour of the famous Indianapolis 500 racetrack.",
    attendees: 134,
    organizer: "Indianapolis Motor Speedway"
  },
  {
    id: 17,
    title: "Circle City Market",
    date: "2024-12-07",
    time: "09:00",
    location: "Monument Circle",
    city: "Indianapolis",
    state: "IN",
    category: "Food & Drink",
    price: "Free",
    image: "https://picsum.photos/400/200?random=17",
    description: "Weekly farmers market in the heart of downtown Indianapolis.",
    attendees: 445,
    organizer: "Indy Market"
  },
  {
    id: 18,
    title: "Indianapolis Symphony Orchestra",
    date: "2024-12-14",
    time: "19:30",
    location: "Hilbert Circle Theatre",
    city: "Indianapolis",
    state: "IN",
    category: "Music",
    price: "$35-85",
    image: "https://picsum.photos/400/200?random=18",
    description: "Classical music performance featuring works by Mozart and Beethoven.",
    attendees: 890,
    organizer: "Indianapolis Symphony"
  },
  {
    id: 19,
    title: "Gateway Arch National Park Tour",
    date: "2024-12-11",
    time: "10:00",
    location: "Gateway Arch",
    city: "St. Louis",
    state: "MO",
    category: "Outdoors",
    price: "$15",
    image: "https://picsum.photos/400/200?random=19",
    description: "Guided tour and tram ride to the top of the iconic Gateway Arch.",
    attendees: 234,
    organizer: "National Park Service"
  },
  {
    id: 20,
    title: "Cardinals Baseball Fan Event",
    date: "2024-12-13",
    time: "18:00",
    location: "Busch Stadium",
    city: "St. Louis",
    state: "MO",
    category: "Sports & Fitness",
    price: "$20",
    image: "https://picsum.photos/400/200?random=20",
    description: "Meet former Cardinals players and tour the stadium during off-season.",
    attendees: 678,
    organizer: "St. Louis Cardinals"
  },
  {
    id: 21,
    title: "Cincinnati Chili Cook-Off",
    date: "2024-12-15",
    time: "12:00",
    location: "Fountain Square",
    city: "Cincinnati",
    state: "OH",
    category: "Food & Drink",
    price: "$10",
    image: "https://picsum.photos/400/200?random=21",
    description: "Annual competition featuring Cincinnati's famous chili restaurants.",
    attendees: 567,
    organizer: "Cincinnati Food Festival"
  },
  {
    id: 22,
    title: "Cincinnati Symphony Holiday Concert",
    date: "2024-12-16",
    time: "19:00",
    location: "Music Hall",
    city: "Cincinnati",
    state: "OH",
    category: "Music",
    price: "$30-75",
    image: "https://picsum.photos/400/200?random=22",
    description: "Holiday classics performed by the renowned Cincinnati Symphony Orchestra.",
    attendees: 1200,
    organizer: "Cincinnati Symphony"
  },
  {
    id: 23,
    title: "October Art Festival",
    date: "2024-10-15",
    time: "12:00",
    location: "Riverside Park",
    city: "Evansville",
    state: "IN",
    category: "Arts & Culture",
    price: "Free",
    image: "https://picsum.photos/400/200?random=23",
    description: "Annual art festival featuring local and regional artists.",
    attendees: 892,
    organizer: "Evansville Arts Council"
  },
  {
    id: 24,
    title: "Halloween Block Party",
    date: "2024-10-31",
    time: "18:00",
    location: "Main Street",
    city: "Evansville",
    state: "IN",
    category: "Family & Kids",
    price: "Free",
    image: "https://picsum.photos/400/200?random=24",
    description: "Family-friendly Halloween celebration with trick-or-treating and games.",
    attendees: 1234,
    organizer: "Downtown Evansville"
  },
  {
    id: 25,
    title: "Nashville Songwriter's Circle",
    date: "2024-11-20",
    time: "19:00",
    location: "The Bluebird Cafe",
    city: "Nashville",
    state: "TN",
    category: "Music",
    price: "$25",
    image: "https://picsum.photos/400/200?random=25",
    description: "Intimate acoustic performance by Nashville's top songwriters.",
    attendees: 90,
    organizer: "The Bluebird Cafe"
  },
  {
    id: 26,
    title: "Louisville Craft Beer Festival",
    date: "2024-11-10",
    time: "15:00",
    location: "Louisville Slugger Field",
    city: "Louisville",
    state: "KY",
    category: "Food & Drink",
    price: "$40",
    image: "https://picsum.photos/400/200?random=26",
    description: "Featuring over 100 craft beers from Kentucky and surrounding states.",
    attendees: 2500,
    organizer: "Kentucky Brewers Association"
  },
  {
    id: 27,
    title: "Chicago Architecture Boat Tour",
    date: "2024-11-05",
    time: "14:00",
    location: "Chicago River",
    city: "Chicago",
    state: "IL",
    category: "Arts & Culture",
    price: "$42",
    image: "https://picsum.photos/400/200?random=27",
    description: "Guided boat tour showcasing Chicago's world-famous architecture.",
    attendees: 156,
    organizer: "Chicago Architecture Foundation"
  }
];